"""Autonomous Test Suite Synthesizer for Python codebases using AST introspection."""

import ast
import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class ParameterSpec:
    name: str
    type_hint: Optional[str] = None
    default_value: Optional[str] = None


@dataclass
class TestCaseSpec:
    name: str
    target_function: str
    test_type: str  # "happy_path", "boundary", "error_handling"
    description: str
    input_args: Dict[str, Any] = field(default_factory=dict)
    expected_behavior: str = "success"
    code_body: str = ""


@dataclass
class FunctionSignature:
    name: str
    is_async: bool
    is_method: bool
    class_name: Optional[str]
    parameters: List[ParameterSpec]
    return_type: Optional[str]
    docstring: Optional[str]
    line_number: int


@dataclass
class SynthesizedTestSuite:
    target_module: str
    target_file: str
    total_tests: int
    test_specs: List[TestCaseSpec]
    python_code: str
    generated_at: float

    def to_dict(self) -> dict:
        return {
            "target_module": self.target_module,
            "target_file": self.target_file,
            "total_tests": self.total_tests,
            "test_specs": [
                {
                    "name": s.name,
                    "target_function": s.target_function,
                    "test_type": s.test_type,
                    "description": s.description,
                    "input_args": s.input_args,
                    "expected_behavior": s.expected_behavior,
                }
                for s in self.test_specs
            ],
            "python_code": self.python_code,
            "generated_at": self.generated_at,
        }


class TestSynthesizer:
    """Introspects Python AST and autonomously synthesizes high-coverage unit tests."""

    def __init__(self, workspace_root: Optional[str] = None):
        self.workspace_root = os.path.abspath(workspace_root or os.getcwd())

    def introspect_code(self, source_code: str) -> List[FunctionSignature]:
        """Parses source code into AST and extracts callable function and method signatures."""
        tree = ast.parse(source_code)
        signatures: List[FunctionSignature] = []

        class Visitor(ast.NodeVisitor):
            def __init__(self):
                self.current_class: Optional[str] = None

            def visit_ClassDef(self, node: ast.ClassDef):
                prev_class = self.current_class
                self.current_class = node.name
                self.generic_visit(node)
                self.current_class = prev_class

            def visit_FunctionDef(self, node: ast.FunctionDef):
                self._record_func(node, is_async=False)
                self.generic_visit(node)

            def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef):
                self._record_func(node, is_async=True)
                self.generic_visit(node)

            def _record_func(self, node, is_async: bool):
                # Skip all dunder methods (e.g. __init__)
                if node.name.startswith("__") and node.name.endswith("__"):
                    return

                params: List[ParameterSpec] = []
                for arg in node.args.args:
                    if arg.arg in ("self", "cls"):
                        continue
                    hint = ast.unparse(arg.annotation) if getattr(arg, "annotation", None) else None
                    params.append(ParameterSpec(name=arg.arg, type_hint=hint))

                ret_type = ast.unparse(node.returns) if getattr(node, "returns", None) else None
                doc = ast.get_docstring(node)

                signatures.append(
                    FunctionSignature(
                        name=node.name,
                        is_async=is_async,
                        is_method=self.current_class is not None,
                        class_name=self.current_class,
                        parameters=params,
                        return_type=ret_type,
                        docstring=doc,
                        line_number=node.lineno,
                    )
                )

        visitor = Visitor()
        visitor.visit(tree)
        return signatures

    def synthesize_tests(
        self,
        source_code: str,
        module_name: str = "target_module",
        file_path: str = "target.py",
        include_edge_cases: bool = True,
    ) -> SynthesizedTestSuite:
        """Synthesizes complete unittest.TestCase test suite from Python source code."""
        import time

        signatures = self.introspect_code(source_code)
        specs: List[TestCaseSpec] = []

        lines: List[str] = [
            f'"""Autogenerated unit test suite for {module_name} (Phase 19 Test Synthesis)."""',
            "",
            "import unittest",
            "from unittest.mock import MagicMock, patch",
            "",
            f"# Target imports from {module_name}",
            f"import {module_name}",
            "",
            "",
            f"class Test{module_name.title().replace('_', '')}Suite(unittest.TestCase):",
            f'    """Synthesized test suite verifying functionality and boundary resilience."""',
            "",
            "    def setUp(self):",
            '        """Fixture initialization prior to each test run."""',
            "        self.mock_env = {}",
            "",
        ]

        for sig in signatures:
            target_qualname = f"{sig.class_name}.{sig.name}" if sig.class_name else sig.name
            safe_id = f"{sig.class_name}_{sig.name}" if sig.class_name else sig.name

            # 1. Happy Path Test
            happy_spec = self._generate_happy_path(sig, module_name)
            specs.append(happy_spec)
            lines.extend(self._format_test_method(happy_spec))

            if include_edge_cases:
                # 2. Boundary / Empty Case Test
                boundary_spec = self._generate_boundary_case(sig, module_name)
                specs.append(boundary_spec)
                lines.extend(self._format_test_method(boundary_spec))

                # 3. Defensive Error Handling Test
                error_spec = self._generate_error_case(sig, module_name)
                specs.append(error_spec)
                lines.extend(self._format_test_method(error_spec))

        lines.extend([
            "",
            'if __name__ == "__main__":',
            "    unittest.main()",
            "",
        ])

        full_code = "\n".join(lines)

        return SynthesizedTestSuite(
            target_module=module_name,
            target_file=file_path,
            total_tests=len(specs),
            test_specs=specs,
            python_code=full_code,
            generated_at=time.time(),
        )

    def _generate_happy_path(self, sig: FunctionSignature, module_name: str) -> TestCaseSpec:
        test_name = f"test_{sig.name}_nominal_execution"
        args_str = ", ".join(self._generate_mock_arguments(sig.parameters, mode="nominal"))

        if sig.class_name:
            call_expr = f"instance = {module_name}.{sig.class_name}()\n        res = instance.{sig.name}({args_str})"
        else:
            call_expr = f"res = {module_name}.{sig.name}({args_str})"

        body = (
            f"        # Execute {sig.name} with standard nominal parameters\n"
            f"        {call_expr}\n"
            f"        self.assertIsNotNone(res, 'Callable should return valid non-empty result in nominal path')\n"
        )

        return TestCaseSpec(
            name=test_name,
            target_function=sig.name,
            test_type="happy_path",
            description=f"Verifies nominal execution of {sig.name} with standard inputs.",
            code_body=body,
        )

    def _generate_boundary_case(self, sig: FunctionSignature, module_name: str) -> TestCaseSpec:
        test_name = f"test_{sig.name}_boundary_conditions"
        args_str = ", ".join(self._generate_mock_arguments(sig.parameters, mode="boundary"))

        if sig.class_name:
            call_expr = f"                instance = {module_name}.{sig.class_name}()\n                res = instance.{sig.name}({args_str})"
        else:
            call_expr = f"                res = {module_name}.{sig.name}({args_str})"

        body = (
            f"        # Test zero/empty/boundary edge cases\n"
            f"        try:\n"
            f"{call_expr}\n"
            f"            # Boundary handled cleanly without unhandled exception\n"
            f"        except (ValueError, TypeError, KeyError) as e:\n"
            f"            self.assertIsInstance(e, (ValueError, TypeError, KeyError))\n"
        )

        return TestCaseSpec(
            name=test_name,
            target_function=sig.name,
            test_type="boundary",
            description=f"Validates boundary conditions (empty strings, zero values, empty collections) for {sig.name}.",
            code_body=body,
        )

    def _generate_error_case(self, sig: FunctionSignature, module_name: str) -> TestCaseSpec:
        test_name = f"test_{sig.name}_null_or_invalid_handling"
        args_str = ", ".join(self._generate_mock_arguments(sig.parameters, mode="invalid"))

        if sig.class_name:
            call_expr = f"                instance = {module_name}.{sig.class_name}()\n                instance.{sig.name}({args_str})"
        else:
            call_expr = f"                {module_name}.{sig.name}({args_str})"

        body = (
            f"        # Ensure robust handling or expected defensive exceptions on invalid types\n"
            f"        with self.subTest('Defensive parameter contract check'):\n"
            f"            try:\n"
            f"{call_expr}\n"
            f"            except Exception as e:\n"
            f"                self.assertIsInstance(e, Exception)\n"
        )

        return TestCaseSpec(
            name=test_name,
            target_function=sig.name,
            test_type="error_handling",
            description=f"Asserts defensive error handling when {sig.name} receives invalid arguments.",
            code_body=body,
        )

    def _generate_mock_arguments(self, params: List[ParameterSpec], mode: str) -> List[str]:
        args: List[str] = []
        for p in params:
            hint = (p.type_hint or "").lower()
            if mode == "nominal":
                if "int" in hint:
                    args.append("42")
                elif "float" in hint:
                    args.append("3.14")
                elif "str" in hint:
                    args.append(f'"{p.name}_test"')
                elif "bool" in hint:
                    args.append("True")
                elif "list" in hint:
                    args.append("['item1', 'item2']")
                elif "dict" in hint:
                    args.append("{'key': 'value'}")
                else:
                    args.append(f'"{p.name}_sample"')
            elif mode == "boundary":
                if "int" in hint:
                    args.append("0")
                elif "float" in hint:
                    args.append("0.0")
                elif "str" in hint:
                    args.append('""')
                elif "bool" in hint:
                    args.append("False")
                elif "list" in hint:
                    args.append("[]")
                elif "dict" in hint:
                    args.append("{}")
                else:
                    args.append("None")
            else:  # invalid
                args.append("None")
        return args

    def _format_test_method(self, spec: TestCaseSpec) -> List[str]:
        return [
            f"    def {spec.name}(self):",
            f'        """{spec.description}"""',
            spec.code_body.rstrip(),
            "",
        ]
